controller:
  replicaCount: 1
  service:
    type: LoadBalancer
  config:
    use-forwarded-headers: "true"
    proxy-real-ip-cidr: "0.0.0.0/0"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
